### ISSUE TITLE
Multiple series of values in the same label

### ISSUE THREAD

**Issue by Fiquee** [sgratzl/chartjs-plugin-hierarchical#42] opened 2023-06-14 07:25 UTC
![image](https://github.com/sgratzl/chartjs-plugin-hierarchical/assets/56692050/7507e4b1-b73c-4270-b6ea-20d3eb0fddb0)

Hi, as image attached, I'm currently trying to implement the hierarchical bar chart with scatter plot. 

Based on the image, I created multiple datasets to make it looked like it stacked on the same label. Is there any way for a label to has multiple series of value and stacked together (should be working the same with the children) similar to the attached image?

**Comment by sgratzl** [comment] 2023-06-15 00:13
can you provide an example using a normal categorical scale?

**Comment by Fiquee** [comment] 2023-06-15 02:16
![image](https://github.com/sgratzl/chartjs-plugin-hierarchical/assets/56692050/f8c5c37c-5fce-41ce-a488-d69795c69963)

It should be like this, for this one I create a list of labels in the dataset 
`const data = {
  labels: ["a","b","c","d"],
  datasets: [{
    label: 'Scatter Dataset',
    data: [{
      x: "a",
      y: 0
    }, {
      x: "a",
      y: 6
    }, {
      x: "b",
      y: 5
    }, {
      x: "b",
      y: 5.5
    },{
      x: "c",
      y: 10
    }, {
      x: "c",
      y: 5
    }, {
      x: "d",
      y: 5.5
    }, {
      x: "c",
      y: 8
    }
    ],
    backgroundColor: 'rgb(255, 99, 132)'
  }],
};`

and I use category type for the scale
`type: 'scatter',
  data: data,
  options: {
    scales: {
      x: {
        type: 'category',
        position: 'bottom'
      }
    }
  }`

**Comment by sgratzl** [comment] 2023-06-24 13:00
I'm surprised that the normal categorical scale works, since it generates some weird labels. Not sure yet how to implement that behavior in this scale

**Comment by sgratzl** [comment] 2023-07-14 01:30
duplicate of #44

**Comment by sgratzl** [comment] 2023-10-18 00:22
closing no time to fix

**Closed by sgratzl** 2023-10-18 00:22 UTC
Labels: question
